"""new fields in gamesession

Revision ID: 4cfd008935f2
Revises: e821fe758258
Create Date: 2025-05-06 15:08:36.613132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cfd008935f2'
down_revision: Union[str, None] = 'e821fe758258'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_sessions', sa.Column('current_turn_user_id', sa.Integer(), nullable=True))
    op.add_column('game_sessions', sa.Column('is_current_turn_active', sa.Boolean(), nullable=True))
    op.add_column('game_sessions', sa.Column('turn_number', sa.Integer(), nullable=True))
    op.add_column('game_sessions', sa.Column('players_order', sa.JSON(), nullable=True))
    op.create_foreign_key(None, 'game_sessions', 'users', ['current_turn_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'game_sessions', type_='foreignkey')
    op.drop_column('game_sessions', 'players_order')
    op.drop_column('game_sessions', 'turn_number')
    op.drop_column('game_sessions', 'is_current_turn_active')
    op.drop_column('game_sessions', 'current_turn_user_id')
    # ### end Alembic commands ###
