"""new field character_id in SessionPlayer model

Revision ID: b6ea85affe4b
Revises: db813e6dcb52
Create Date: 2025-04-23 01:24:58.208499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6ea85affe4b'
down_revision: Union[str, None] = 'db813e6dcb52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session_players', sa.Column('character_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'session_players', 'characters', ['character_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'session_players', type_='foreignkey')
    op.drop_column('session_players', 'character_id')
    # ### end Alembic commands ###
